### ISSUE TITLE
Ability to create routes from yaml files

### ISSUE THREAD

**Issue by malukenho** [klein/klein.php#184]
With this, we can centralize the routing settings for our project created as _Klein.php_. Besides providing us greater flexibility and mobility between exchange routes, classes, methods and verbs.

Here is my proposal: The `yaml` files should describe the necessary class work without the need for further settings.

I **SUGGEST** the following syntax for the `yaml` files:

``` yaml
- base_path: /blog

- routes:
  - index: [/index, someClass.indexAction, GET]
  - contact: [/contact, someClass.contactAction, GET]
  - about: [/about, someClass.aboutAction, GET]
```

What do you think about this?
